# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-17 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingRoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('ID', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
