# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingRoom', '0002_auto_20191121_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
