# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingRoom', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='encode',
            field=models.TextField(default=''),
        ),
    ]
