# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-21 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingRoom', '0003_auto_20191121_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('ID', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('condition', models.IntegerField(default=0)),
                ('roomInfo', models.TextField(default='')),
                ('reserveInfo', models.TextField(default='')),
            ],
        ),
    ]
