# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingRoom', '0004_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
